(lang dune 3.19)

(name rng_site)

(generate_opam_files true)

(source
 (github CharlesAverill/rng))

(authors "Charles Averill <charlesaverill20@gmail.com>")

(maintainers "Charles Averill <charlesaverill20@gmail.com>")

(license LICENSE)

(documentation https://www.charles.systems/rng/)

; (using js_of_ocaml 5.3)

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
